feat(delete_type_scholarship): añadir funcionalidad de eliminación de…
Jun-266/becas-filantropia pull request #16
Opened 2023-10-10 05:03 UTC by santiagoprado21

Agrega la capacidad de eliminar un tipo de beca proporcionando su nombre. Esta funcionalidad permite a los usuarios eliminar tipos de beca existentes desde la interfaz

2023-10-11 16:45 UTC, JD-Lora1 requested changes
Revisate los comentarios :D

2023-10-11 16:45 UTC, JD-Lora1 commented on app_becas/models.py
> +    name = models.CharField(max_length=50, primary_key=True)
Cuando haces los cambios en el model, también deberían de quedar reflejados en las migrations, para que también se actualice en la base de datos. Es decir, cambia esa etiqueta también en el migrations

2023-10-11 16:45 UTC, JD-Lora1 commented on app_becas/forms/scholarship_forms.py
>  class Form_add_calendar(forms.Form):
Si este forms es para scholarship, no debería ir este último form de Calendar

2023-10-11 16:45 UTC, JD-Lora1 commented on app_becas/forms/scholarship_forms.py
> -    type_scholarship_choices = [(obj.id, obj.name) for obj in type_scholarship_objects]
Acá, si bien se puede hacer lo del (obj.name, obj.name)
Donde en el diccionario que se crea se toma por key el mismo name. Recuerdo que esto lo hicimos en el meet. Pero, también recuerdo que te salía error en esta línea por obj.id, porque no estaba definido. Si bien en el migrations se autogenera un campo id automático, esto solo se ve reflejado en la base de datos. Deberías de hacer el cambio en el model de TypeScholarship, es decir añadir ese campo.

2023-10-12 00:34 UTC, JD-Lora1 approved these changes
Buen trabajo Santi

2023-10-12 03:57 UTC, Jun-266 commented
👍

2023-10-12 03:57 UTC, merged