Search scholarship by name hecho
Jun-266/becas-filantropia pull request #19
Opened 2023-10-15 18:44 UTC by santiagoprado21

2023-10-17 16:12 UTC, JD-Lora1 requested changes
Mira los cambios. Trintran

2023-10-17 16:12 UTC, JD-Lora1 commented on app_becas/migrations/0002_scholarship_temp.py
> +                ('auto_id', models.UUIDField(default=uuid.uuid4, editable=False)),
tu uuid debería de estar es como String, además debería ser tu primary key

2023-10-17 16:12 UTC, JD-Lora1 commented on app_becas/migrations/0008_alter_typescholarship_name.py
> +            field=models.CharField(max_length=50, primary_key=True, serialize=False),
Noto que hiciste los cambios acá. Entonces el cambio que debes de hacer es que todo quede en un mismo archivo, un mismo migration, máximo en 2. Actualmente hay 6

2023-10-17 16:12 UTC, JD-Lora1 commented on app_becas/models.py
> +        return str(self.auto_id)
No debes cambiar el "toString" de python. Si no que debes de hacer ese cambio directamente en el modelo. Es decir, no queda en otra función aparte, queda en el mismo model, definido así como lo tienes. Lo que vendría siendo un Charfield, cuyo valor por defecto estará dado por un uuid,

2023-10-23 13:36 UTC, JD-Lora1 approved these changes

2023-10-23 13:37 UTC, Jun-266 approved these changes

2023-10-23 13:37 UTC, merged