Feat 27
Jun-266/becas-filantropia pull request #20
Opened 2023-10-17 03:00 UTC by JeisonLasprilla

2023-10-17 16:23 UTC, JD-Lora1 requested changes
Ahí te deje unos comentarios c:

2023-10-17 16:23 UTC, JD-Lora1 commented on app_becas/migrations/0001_initial.py
> +                ('auto_id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
Jeison mi bro, acordate lo que hablamos. Estos campos deben ser un string, que si bien es cierto que su valor nace de un uuid, no vamos a colocarlos así en el model, sino que en el model quedan como string, es decir, CharField

2023-10-17 16:23 UTC, JD-Lora1 commented on app_becas/migrations/0001_initial.py
> +                ('auto_id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
Por cierto, por que cambias los model de otras calses xd
I mean, está bien, pero tienes que avisar, por que estas "clases"/objetos, los utilizan otras personas en otras branches también

2023-10-17 16:23 UTC, JD-Lora1 commented on app_becas/templates/manage_user.html
Bonito bonito

2023-10-17 16:23 UTC, JD-Lora1 commented on app_becas/views/manage_user.py
> -@method_decorator(login_required, name='dispatch')
Para gestionar los usuarios no es necesario que se logueen primero?, dudita

2023-10-23 12:39 UTC, JD-Lora1 approved these changes

2023-10-23 12:40 UTC, santiagoprado21 approved these changes

2023-10-23 12:40 UTC, merged