Feat student
Jun-266/becas-filantropia pull request #24
Opened 2023-10-30 14:59 UTC by JeisonLasprilla

2023-10-30 15:36 UTC, JD-Lora1 requested changes
El agregar Major/Carrera, debería ir como opcional, dentro de el agregar estudiante. 
por cierto, Seguro que es opcional?
Además, cuando esta se cree (major) , no debería aparecer como modificable el ID autogenerado. Lo otro esque este Major es una tabla, por lo cual, cuando se cree el estudiante, deberá de desplegar una lista

Acuerdate de mostrar los estudiantes como objetos, con un preview, como nos indicado domi, similar a mini tarjeticas con un par de datos relevante. Deja esta vista que tienes, como secundaria (es decir, no la elimines) y crea otra dentro de ese mismo html, con un condicional de Jinja, para que se muestre en formato tarjetitas o en formato lista (los estudiantes)

2023-10-30 15:36 UTC, JD-Lora1 commented on app_becas/templates/modify_student.html
> +                        <h1 class="card-title mx-3 mt-2">Major</h1>
Debería ser "Carrera" no Major

2023-11-06 04:42 UTC, JD-Lora1 approved these changes
Nais

2023-11-13 16:02 UTC, Jun-266 approved these changes
👍

2023-11-13 16:03 UTC, merged