Feat(becas) : Registrar una nueva beca y generacion automatica ID
Jun-266/becas-filantropia pull request #4
Opened 2023-10-04 19:55 UTC by santiagoprado21

2023-10-04 20:00 UTC, JD-Lora1 commented on app_becas/models.py
> -    def __str__(self):
Este debes dejarlo, para que quede dentro de la clase

2023-10-04 20:02 UTC, JD-Lora1 requested changes
solo has ese cambio

2023-10-04 20:07 UTC, JD-Lora1 approved these changes

2023-10-05 20:30 UTC, JeisonLasprilla commented
Aprovado

2023-10-05 20:36 UTC, JeisonLasprilla approved these changes

2023-10-05 20:36 UTC, merged